//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVehicleSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public decimal SalesID { get; set; }
        public decimal VehicleID { get; set; }
        public decimal CustomerID { get; set; }
        public decimal ShowroomID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Showroom Showroom { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
