//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVehicleSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public decimal VehicleID { get; set; }
        public string VehicleName { get; set; }
        public string VehicleModel { get; set; }
        public decimal DealerID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TotalStock { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
